// screens/knowledge/quickaccess/resourceData.js
// Singapore-only news + official advisories (no video/pdf/tool/weather/CPR)

export const RESOURCE_HUB_DATA = {
  featured: [
    {
      id: 'sg-press-centre',
      title: 'SG Press Centre (All Gov)',
      subtitle: 'Unified press releases from Singapore Government',
      provider: 'Gov.sg',
      url: 'https://www.sgpc.gov.sg/',
      type: 'site',
      tags: ['government', 'press'],
      icon: '🏛️',
    },
    {
      id: 'cna-sg-latest',
      title: 'CNA — Singapore',
      subtitle: 'Channel NewsAsia (Singapore)',
      provider: 'Channel NewsAsia',
      url: 'https://www.channelnewsasia.com/singapore',
      type: 'site',
      tags: ['news'],
      icon: '📰',
    },
    {
      id: 'st-singapore',
      title: 'The Straits Times — Singapore',
      subtitle: 'ST Singapore section',
      provider: 'The Straits Times',
      url: 'https://www.straitstimes.com/singapore',
      type: 'site',
      tags: ['news'],
      icon: '🗞️',
    },
    {
      id: 'todayonline-sg',
      title: 'TODAY — Singapore',
      subtitle: 'Local breaking news and features',
      provider: 'TODAY',
      url: 'https://www.todayonline.com/singapore',
      type: 'site',
      tags: ['news'],
      icon: '📰',
    },
  ],

  // Official / agencies (stable newsroom/media centre links)
  official: [
    {
      id: 'pmo-newsroom',
      title: 'PMO — Newsroom',
      subtitle: 'Prime Minister’s Office news and speeches',
      provider: 'Prime Minister’s Office',
      url: 'https://www.pmo.gov.sg/Newsroom',
      type: 'site',
      tags: ['government'],
      icon: '🏢',
    },
    {
      id: 'moh-newsroom',
      title: 'MOH — Newsroom',
      subtitle: 'Ministry of Health news and updates',
      provider: 'Ministry of Health',
      url: 'https://www.moh.gov.sg/newsroom/',
      type: 'site',
      tags: ['health'],
      icon: '🩺',
    },
    {
      id: 'nea-dengue',
      title: 'NEA — Dengue Clusters',
      subtitle: 'Cluster map and alerts',
      provider: 'NEA',
      url: 'https://www.nea.gov.sg/dengue-zika/dengue/dengue-clusters',
      type: 'site',
      tags: ['health', 'dengue'],
      icon: '🦟',
    },
    {
      id: 'ica-entering',
      title: 'ICA — Entering Singapore',
      subtitle: 'Entry/transit/departure info (incl. SG Arrival Card)',
      provider: 'ICA',
      url: 'https://www.ica.gov.sg/enter-transit-depart/entering-singapore',
      type: 'site',
      tags: ['travel', 'border'],
      icon: '🛃',
    },
    {
      id: 'mas-news',
      title: 'MAS — News',
      subtitle: 'News releases, speeches and enforcement',
      provider: 'Monetary Authority of Singapore',
      url: 'https://www.mas.gov.sg/news',
      type: 'site',
      tags: ['finance', 'regulation'],
      icon: '🏦',
    },
    {
      id: 'psd-media',
      title: 'PSD — Media Releases',
      subtitle: 'Public Service Division announcements',
      provider: 'Public Service Division',
      url: 'https://www.psd.gov.sg/newsroom/media-releases/',
      type: 'site',
      tags: ['public-service'],
      icon: '📣',
    },
    {
      id: 'mti-press',
      title: 'MTI — Press Releases',
      subtitle: 'Trade & industry policies and initiatives',
      provider: 'Ministry of Trade and Industry',
      url: 'https://www.mti.gov.sg/Newsroom/Press-Releases',
      type: 'site',
      tags: ['economy', 'trade'],
      icon: '📈',
    },
    {
      id: 'enterprisesg-media',
      title: 'EnterpriseSG — Media Centre',
      subtitle: 'Updates, speeches and news for businesses/SMEs',
      provider: 'Enterprise Singapore',
      url: 'https://www.enterprisesg.gov.sg/resources/media-centre',
      type: 'site',
      tags: ['business', 'sme'],
      icon: '🏭',
    },
    {
      id: 'mddi-newsroom',
      title: 'MDDI — Newsroom',
      subtitle: 'Digital development & ICT updates',
      provider: 'MDDI',
      url: 'https://www.mddi.gov.sg/newsroom/',
      type: 'site',
      tags: ['digital', 'ict'],
      icon: '💻',
    },
  ],

  // Analysis / explainers
  learning: [
    {
      id: 'govsg-explainers',
      title: 'Gov.sg — Explainers',
      subtitle: 'Policy and hot-topic explainers',
      provider: 'Gov.sg',
      url: 'https://www.gov.sg/explainers/',
      type: 'article',
      tags: ['analysis', 'explainer'],
      icon: '📘',
    },
    {
      id: 'factually',
      title: 'Factually — Corrections & Clarifications',
      subtitle: 'Government fact-checks and clarifications',
      provider: 'Gov.sg',
      url: 'https://www.factually.gov.sg/corrections-and-clarifications',
      type: 'article',
      tags: ['fact-check', 'pofma'],
      icon: '✔️',
    },
    {
      id: 'st-insight',
      title: 'ST — Insight',
      subtitle: 'The Straits Times in-depth section',
      provider: 'The Straits Times',
      url: 'https://www.straitstimes.com/tags/insight',
      type: 'article',
      tags: ['analysis'],
      icon: '📙',
    },
    {
      id: 'cna-sg-features',
      title: 'CNA — Singapore (Features/Explainers)',
      subtitle: 'Singapore features and explainers (channel hub)',
      provider: 'Channel NewsAsia',
      url: 'https://www.channelnewsasia.com/singapore',
      type: 'article',
      tags: ['analysis'],
      icon: '📗',
    },
  ],

  faqs: [
    { q: 'How do I view only “Official” advisories?', a: 'Use the filter at the top and choose “Official”.' },
    { q: 'How do I bookmark a link?', a: 'Tap the ☆ on the card to add/remove it from bookmarks.' },
  ],
};
